stages:
  - build
  - publish 

build-vm:
  stage: build
  script:
    - vagrant up
    - vagrant halt
    - if (Test-Path kite-dev.box) { Remove-Item kide-dev.box }
    - vagrant package --output kite-dev.box
  artifacts:
    paths:
    - kite-dev.box
    expire_in: 1 day
  tags:
    - vagrant
  except:
    - branches

publish-vm:
  stage: publish
  script:
    - vagrant cloud auth login
    - vagrant cloud publish einfachIT/kite-vm $CI_COMMIT_TAG virtualbox kite-dev.box --release 
  tags:
    - vagrant
  only:
    - tags
  except:
    - master
    - branches

# create-box:
#   stage: package
#   script:
#     - vagrant package --output kite-dev.box
#   tags:
#     - vagrant


