stages:
  - build
#   - package

build-vm:
  stage: build
  script:
    - vagrant up
    - vagrant package --output kite-dev.box
  tags:
    - vagrant

# create-box:
#   stage: package
#   script:
#     - vagrant package --output kite-dev.box
#   tags:
#     - vagrant


