stages:
  - build
  - publish 

build-vm:
  stage: build
  script:
    - vagrant up
    - vagrant halt
  tags:
    - vagrant
  only:
    - master

publish-vm:
  stage: publish
  script:
    - vagrant up
    - vagrant halt
    - if (Test-Path kite-dev.box) { Remove-Item kide-dev.box }
    - vagrant package --output kite-dev.box
    - vagrant cloud auth login
    - vagrant cloud publish einfachIT/kite-vm $CI_COMMIT_TAG virtualbox kite-dev.box --release 
  tags:
    - vagrant
  only:
    - tags
