stages:
  - build
  - publish 

build-vm:
  stage: build
  script:
    - vagrant up
    - vagrant halt
    - IF EXIST kite-dev.box del hite-dev.box
    - vagrant package --output kite-dev.box
  artifacts:
    paths:
    - kide-dev.box
    expire_in: 1 day
  tags:
    - vagrant

publish-vm:
  stage: publish
  script:
    - vagrant cloud auth login
    - vagrant cloud publish einfachIT/kite-vm $CI_COMMIT_TAG virtualbox kite-dev.box --release 
  only:
    - tags
  except:
    - master

# create-box:
#   stage: package
#   script:
#     - vagrant package --output kite-dev.box
#   tags:
#     - vagrant


